### ISSUE TITLE
Broken data packs

### ISSUE THREAD

**Issue by Estrelaura** [Micalobia/Full-Slabs#25]
Not much info since it doesn't crash the game, but some processors from the Repurposed Structures mod don't work with the mod installed. The built-in data pack fails to be read and no world is able to open. The crumbs of info the console gives:

> [16:38:05] [Render thread/WARN]: Failed to load datapacks, can't proceed with server load
com.google.gson.JsonParseException: Error loading registry data: Not a json array: {"processors":[{"rules":[{"output_state":{"Name":"minecraft:gilded_blackstone"},"input_predicate":{"block":"minecraft:polished_blackstone_bricks","probability":0.006,"predicate_type":"minecraft:random_block_match"},"location_predicate":{"predicate_type":"minecraft:always_true"}},{"output_state":{"Name":"minecraft:blackstone"},"input_predicate":{"block":"minecraft:polished_blackstone_bricks","probability":0.05,"predicate_type":"minecraft:random_block_match"},"location_predicate":{"predicate_type":"minecraft:always_true"}},{"output_state":{"Name":"minecraft:cracked_polished_blackstone_bricks"},"input_predicate":{"block":"minecraft:polished_blackstone_bricks","probability":0.1,"predicate_type":"minecraft:random_block_match"},"location_predicate":{"predicate_type":"minecraft:always_true"}},{"output_state":{"Name":"minecraft:chiseled_polished_blackstone"},"input_predicate":{"block":"minecraft:polished_blackstone_bricks","probability":0.05,"predicate_type":"minecraft:random_block_match"},"location_predicate":{"predicate_type":"minecraft:always_true"}},{"output_state":{"Properties":{"type":"bottom","waterlogged":"false"},"Name":"minecraft:blackstone_slab"},"input_predicate":{"block":"minecraft:polished_blackstone_brick_slab","probability":0.1,"predicate_type":"minecraft:random_block_match"},"location_predicate":{"predicate_type":"minecraft:always_true"}}],"processor_type":"minecraft:rule"}]}
	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.9) ~[?:?]
	at net.minecraft.util.registry.DynamicRegistryManager.method_34849(DynamicRegistryManager:221) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at net.minecraft.util.registry.DynamicRegistryManager.load(DynamicRegistryManager:221) ~[?:?]
	at net.minecraft.util.registry.DynamicRegistryManager.load(DynamicRegistryManager:212) ~[?:?]
	at net.minecraft.util.dynamic.RegistryOps.method_36575(RegistryOps:57) ~[?:?]
	at net.minecraft.util.dynamic.RegistryOps.method_36574(RegistryOps:51) ~[?:?]
	at net.minecraft.client.MinecraftClient.createSaveProperties(MinecraftClient:1924) ~[?:?]
	at net.minecraft.client.MinecraftClient.method_29604(MinecraftClient:2155) ~[?:?]
	at net.minecraft.client.MinecraftClient.startIntegratedServer(MinecraftClient:1999) ~[?:?]
	at net.minecraft.client.MinecraftClient.startIntegratedServer(MinecraftClient:1939) ~[?:?]
	at net.minecraft.client.gui.screen.world.WorldListWidget$Entry.start(WorldListWidget:437) ~[?:?]
	at net.minecraft.client.gui.screen.world.WorldListWidget$Entry.play(WorldListWidget:343) ~[?:?]
	at net.minecraft.client.gui.screen.world.WorldListWidget$Entry.mouseClicked(WorldListWidget:274) ~[?:?]
	at net.minecraft.client.gui.widget.EntryListWidget.mouseClicked(EntryListWidget:359) ~[?:?]
	at net.minecraft.client.gui.ParentElement.mouseClicked(ParentElement:27) ~[?:?]
	at net.minecraft.client.Mouse.method_1611(Mouse:94) ~[?:?]
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen:490) ~[?:?]
	at net.minecraft.client.Mouse.onMouseButton(Mouse:94) ~[?:?]
	at net.minecraft.client.Mouse.method_22686(Mouse:165) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:101) ~[?:?]
	at net.minecraft.client.Mouse.method_22684(Mouse:165) ~[?:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem:190) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1140) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:728) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:217) [intermediary-minecraft-1.17.1-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]

**Comment by Micalobia** [comment]
If you could drop a complete mod list if you're comfortable with that, I'll look into this soon

**Comment by Estrelaura** [comment]
It's quite large, but here it is. I can provide more info or run more tests if needed, but i tested quite a lot to narrow down this conflict already.

> [16:30:40] [main/INFO]: [FabricLoader] Loading 287 mods:
	- accurateblockplacement@1.0.10
	- adaptivebrightness@1.0.2
	- advanced_runtime_resource_pack@0.4.3
	- advancementplaques@1.4.0
	- advancements-enlarger@0.2.4
	- amecsapi@1.1.5+mc21w16a
	- annotateddi@2.0.3+1.17.1
	- antighost@1.17.1-fabric0.36.1-1.1.4
	- aopalliance_aopalliance@1.0
	- appleskin@mc1.17-2.1.3
	- architectury@2.5.28
	- asa@1.2
	- atmosfera@2.0.0+mc1.17
	- audaki_cart_engine@1.0.1
	- augmentedautojump@1.1.0
	- authme@1.5.0
	- auto_third_person@1.1.0
	- autoconfig1u@3.3.1
	- axesareweapons@1.3-1.17
	- axolotlitemfix@1.1.2
	- beaconoverhaul@1.4.1+1.17
	- bedrockify@1.2.0+mc1.17.1
	- bedrockwaters@1.5.0+1.17.1
	- betterdungeons@1.17-1.0.1
	- bettereating@0.3.0
	- betterf3@1.1.5
	- bettermineshafts@1.17-1.0.1
	- bettermounthud@1.1.2
	- betterstrongholds@1.17-1.1.1
	- betterthirdperson@1.5.0
	- big_items_duh@1.0.2+mc1.17-rc2
	- blastproof_netherite@2.0.0+mc1.17
	- blur@2.1.0
	- breakfree@1.0.0
	- cakechomps@1.4.0-1.17
	- camp_fires_cook_mobs@1.2.1+MC1.17-1.17.1
	- carpet@1.4.47
	- carpet-extra@1.4.43
	- carpet-fixes@1.17.1-1.1.0+v210919
	- carpet-tis-addition@1.22.0+build.678
	- cartloaders@0.0.2
	- cauldronconcrete@1.0.0+21w16a-fabric
	- cauldronriptide@1.1-mc1.17-fabric
	- cavebiomes@0.6.3
	- chainsuspension@1.0.0
	- clear-skies@1.5.70
	- clientsidenoteblocks@2.0
	- cloth-api@2.0.54
	- cloth-basic-math@0.5.1
	- cloth-client-events-v0@2.0.54
	- cloth-common-events-v1@2.0.54
	- cloth-config2@5.0.38
	- cloth-datagen-api-v1@2.0.54
	- cloth-scissors-api-v1@2.0.54
	- cloth-utils-v1@2.0.54
	- colorfulsubtitles@1.0.0
	- com_electronwill_night-config_core@3.6.3
	- com_electronwill_night-config_toml@3.6.3
	- com_focamacho_sealconfig@1.2.2
	- com_google_inject_guice@5.0.1
	- com_moandjiezana_toml_toml4j@0.7.2
	- com_velocitypowered_velocity-native@1.1.0-SNAPSHOT
	- controlling@1.1.2
	- couplings@1.5.0+1.17
	- creativeonepunch@1.2
	- crosshairmod@0.3.1
	- crowdin-translate@1.3+1.17
	- customstars@0.5
	- datareload@1.1
	- deathcoords@1.0.0
	- debrand@1.0.2
	- detailab@2.5+1.17.1-fabric
	- discerning_furnace@1.0.3+MC1.17-1.17.1
	- dontdropit@2.3.2+1.17
	- dual_riders@1.0.5
	- durabilityspeed@1.4.0
	- dynamicfps@2.0.5
	- dynmus@1.3.0
	- easyautocrafting@1.1+1.17
	- eatinganimationid@1.2
	- elytraprotection@1.17-0.1.1
	- enchantment_lore@1.2.1+MC1.17.1
	- enchantmentdescriptions@4.0.1
	- enchantmenttweaker@0.0.1b
	- enhanced_attack_indicator@1.0.2+1.17
	- enhancedblockentities@0.5+1.17
	- enhancedcelestials@2.0.5
	- entityculling@1.3.3
	- extrasounds@1.4.1
	- extrasucchopper@1.0+1.17
	- fabric@0.40.1+1.17
	- fabric-api-base@0.3.0+a02b446313
	- fabric-api-lookup-api-v1@1.3.0+cbda931818
	- fabric-biome-api-v1@3.2.0+cbda931818
	- fabric-blockrenderlayer-v1@1.1.5+a02b446318
	- fabric-command-api-v1@1.1.3+5ab9934c18
	- fabric-commands-v0@0.2.2+92519afa18
	- fabric-containers-v0@0.1.12+cbda931818
	- fabric-content-registries-v0@0.3.0+cbda931818
	- fabric-crash-report-info-v1@0.1.5+be9da31018
	- fabric-diagonal-panes@0.5.0
	- fabric-dimensions-v1@2.0.11+6cefd57718
	- fabric-entity-events-v1@1.2.3+87cc6e4c18
	- fabric-events-interaction-v0@0.4.10+fc40aa9d18
	- fabric-events-lifecycle-v0@0.2.1+92519afa18
	- fabric-game-rule-api-v1@1.0.7+cbda931818
	- fabric-item-api-v1@1.2.4+a02b44633d
	- fabric-item-groups-v0@0.2.10+b7ab612118
	- fabric-key-binding-api-v1@1.0.4+cbda931818
	- fabric-keybindings-v0@0.2.2+36b77c3e18
	- fabric-language-kotlin@1.6.4+kotlin.1.5.30
	- fabric-lifecycle-events-v1@1.4.4+a02b44633d
	- fabric-loot-tables-v1@1.0.4+a02b446318
	- fabric-mining-levels-v0@0.1.3+92519afa18
	- fabric-models-v0@0.3.0+a02b446318
	- fabric-networking-api-v1@1.0.13+cbda931818
	- fabric-networking-blockentity-v0@0.2.11+a02b446318
	- fabric-networking-v0@0.3.2+92519afa18
	- fabric-object-builder-api-v1@1.10.9+cbda931818
	- fabric-object-builders-v0@0.7.3+a02b446318
	- fabric-particles-v1@0.2.4+a02b446318
	- fabric-permissions-api-v0@0.1-SNAPSHOT
	- fabric-registry-sync-v0@0.7.10+e2961fee18
	- fabric-renderer-api-v1@0.4.4+cbda931818
	- fabric-renderer-indigo@0.4.8+cbda931818
	- fabric-renderer-registries-v1@3.2.3+4658223018
	- fabric-rendering-data-attachment-v1@0.1.5+a02b446313
	- fabric-rendering-fluids-v1@0.1.14+4658223018
	- fabric-rendering-v0@1.1.4+4658223018
	- fabric-rendering-v1@1.8.2+ffb6d41e18
	- fabric-resource-loader-v0@0.4.8+a00e834b18
	- fabric-screen-api-v1@1.0.4+198a96213d
	- fabric-screen-handler-api-v1@1.1.8+cbda931818
	- fabric-structure-api-v1@1.1.13+5ab9934c18
	- fabric-tag-extensions-v0@1.2.1+b06cb95b18
	- fabric-textures-v0@1.0.6+a02b446318
	- fabric-tool-attribute-api-v1@1.2.12+b7ab61213d
	- fabric-transfer-api-v1@1.3.1+4658223018
	- fabricloader@0.11.6
	- fabulousclouds@0.2.3
	- fairhorsestats@1.0.0
	- fallingblocktweaks@1.0.0+1.16.5-fabric
	- fallingleaves@1.7.3+1.17.1
	- farsighted-mobs@1.0a-1.17
	- fefafly@1.0.0
	- ferritecore@3.0.3
	- fireplacelib@5.7.1+1.17.1
	- fireworkfrenzy@1.5
	- fishonaleash@1.17-1.0.0
	- fishybears@0.1
	- flytre_lib@0.2.21
	- freezma@1.17.1-1
	- fruitful@1.0.1
	- fuelinfo@1.0
	- full_slabs@3.0.0
	- ghastly_wail@1.0.3+MC1.17-1.17.1
	- goosiklib@0.1.0
	- grindenchantments@1.4.0+1.17.1
	- grindstoneismadeofstone@1.0
	- hatlist@1.2
	- herdspanic@1.0.3
	- homecamp@2.0.1+1.17.1
	- hotfurnace@1.0
	- hydrogen@0.3
	- illuminations@1.7.2
	- indium@1.0.0+mc1.17.1
	- indypets@0.7.0
	- infinitywaterbucket@1.4.1-mc1.17-fabric
	- inspecio@1.1.0+1.17
	- interdimensional-map-markers@1.0.0
	- iris@1.1.2+build.9
	- itemmodelfix@1.0.2+1.17
	- java@16
	- javax_inject_javax_inject@1
	- justenoughkeys@0.2.2
	- kirin@1.9.1
	- krypton@0.1.4
	- lambdabettergrass@1.2.1+1.17
	- lambdynlights@2.0.2+1.17
	- lapisreserve@1.0.8
	- lazydfu@0.1.2
	- light-fix@1.0.0
	- lithium@0.7.4
	- loading-timer@1.5.0-Beta1
	- lunaar-carpet-addons@0.5.0
	- maelstrom_library@1.2.1-1.17-pre1
	- mcwifipnp@1.4.7
	- minecraft@1.17.1
	- minitweaks@1.1.2
	- mixintrace@1.1.0+1.17
	- mm@2.2
	- mobs_attempt_parkour@0.2.3-1.17-pre1
	- modmenu@2.0.12
	- mojangster@1.17-3.0.1
	- mostructures@1.3.0-pre1-1.17.1
	- mousewheelie@1.7.3+mc1.17.1-pre1
	- musicdr@1.2.1
	- namepain@1.4.0
	- nbexpand@2.0.1
	- ne-v-seti@0.1.6-1.17
	- nethermap@1.5.0-1.17.1
	- no-potion-offset@${version}
	- not-that-cc@1.0
	- notenoughanimations@1.3.0
	- notenoughcrashes@3.6.2+1.17.1
	- omega-config@1.0.8
	- onsoulfire@1.17-1
	- org_aperlambda_lambdajcommon@1.8.1
	- org_codehaus_groovy_groovy@3.0.8
	- org_codehaus_groovy_groovy-jsr223@3.0.8
	- org_jetbrains_kotlin_kotlin-reflect@1.5.30
	- org_jetbrains_kotlin_kotlin-stdlib@1.5.30
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7@1.5.30
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8@1.5.30
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm@1.5.1
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8@1.5.1
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm@1.2.2
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm@1.2.2
	- pale@1.0.0
	- particlerain@1.5.0
	- peepingcreepers@1.1-1.17
	- perfectaccuracy@1.1
	- pettable@1.2.0
	- pickblockstate@1.0.0+1.17
	- pingspam@1.2.2-1.17
	- pling@1.4.0
	- powershot@1.2.0-1.17-fabric
	- ppp@1.3.0
	- presencefootsteps@r32-1.17-rc1
	- puddles@1.1.0
	- quickspyglasser@0.3.0
	- quitconfirm@1.3
	- rad@1.0.1
	- rainbow-shenanigans@1.0.0
	- reach-entity-attributes@2.1.1
	- recipecache@0.2.0-1.17.1
	- repurposed_structures@2.3.4+1.17.1
	- reroll@1.3.0-1.17.1
	- rocket_minecarts@1.0.0
	- roughlyenoughitems@6.0.279-alpha
	- rug@1.17.1-1.1.13
	- rutreplantswamp@0.0.1
	- satin@1.6.0-nightly.1.17-pre3
	- scaryplayer@1.1.0
	- scorch@1.1.2
	- screenshotclipboard@1.0.6
	- searchablecontainers@1.3
	- secondchance@1.1.0
	- servertick@1.5
	- sgui@1.0.0-rc3-1.17.1
	- sihywtcamc@1.4.1+1.17.1
	- sihywtcamd@1.5.2+1.17.1
	- simplyimprovedterrain@0.4.0.3-Fabric-1.17
	- skinlayers@1.1.0
	- slight-gui-modifications@2.0.1
	- slimyfloor@1.17.1-1.2.0
	- smoothscrollingeverywhere@3.0.3-unstable
	- smoothswapping@0.4.2
	- snowundertrees@1.0.0
	- sodium@0.3.2+IRIS2-build.9
	- soundphysics@2.0.0
	- spruceui@3.3.0+1.17
	- spyzoom@1.0.1
	- starlight@1.0.0+fabric.73f6d37
	- stat_check@1.1.0
	- stonevaults@1.1.0
	- taxfreelevels@1.2.1
	- telepistons@1.0.2
	- tooltipfix@1.0.3-1.16
	- torohealth@1.17.1-fabric-12
	- transliterationlib@1.1.0
	- treefax@1.3.0
	- treefelling@1.0.0
	- tweed@3.0.0-beta.26
	- undergroundambientlighting@2.0.0
	- unsaddleeeee@1.0+mc1.17-Fabric
	- vectorientation@1.0.1a
	- vehiclefix@1.1
	- villager_see_villager_do@1.1.1+MC1.17-1.17.1
	- villagers@1.0+1.16.3
	- visuality@0.1.3
	- waig@1.0.0
	- wandering_collector@1.0.2+mc1.17
	- waterdripsound@1.17-0.2.2
	- waveycapes@1.0.3
	- xpbeacons@7.0
	- yungsapi@1.17-Fabric-16
